# query allPlayers ($searchString: String) {
query allPlayers {
  # Players (searchString: $searchString) {
    Players {
    id
    firstname
    lastname
    team
    height
    weight
    age
  }
}